# Linker L20 - KeyVectorOptimizer (MediaPipe video/camera input)
# norm_delta=0.06: higher than AVP because monocular depth is noisier

optimizer:
  type: "KeyVectorOptimizer"

robot:
  type: "linker_l20"

retarget:
  huber_delta: 2.0
  norm_delta: 0.06
  lp_alpha: 0.4
  key_vectors:
    # thumb
  - {origin: hand_base_link, task: thumb_proximal, origin_kp: 0, task_kp: 2, scale: 
      1.126}
  - {origin: hand_base_link, task: thumb_distal, origin_kp: 0, task_kp: 3, scale: 
      1.051}
  - {origin: hand_base_link, task: thumb_distal, origin_kp: 0, task_kp: 4, 
      task_offset: [-0.0110, 0.0, 0.0277], scale: 0.988}
    # index
  - {origin: hand_base_link, task: index_middle, origin_kp: 0, task_kp: 6, scale: 
      1.526}
  - {origin: hand_base_link, task: index_distal, origin_kp: 0, task_kp: 7, scale: 
      1.457}
  - {origin: hand_base_link, task: index_distal, origin_kp: 0, task_kp: 8, 
      task_offset: [-0.0135, 0.0, 0.0188], scale: 1.366}
    # middle
  - {origin: hand_base_link, task: middle_middle, origin_kp: 0, task_kp: 10, 
      scale: 1.53}
  - {origin: hand_base_link, task: middle_distal, origin_kp: 0, task_kp: 11, 
      scale: 1.454}
  - {origin: hand_base_link, task: middle_distal, origin_kp: 0, task_kp: 12, 
      task_offset: [-0.0135, 0.0, 0.0188], scale: 1.363}
    # ring
  - {origin: hand_base_link, task: ring_middle, origin_kp: 0, task_kp: 14, scale: 
      1.549}
  - {origin: hand_base_link, task: ring_distal, origin_kp: 0, task_kp: 15, scale: 
      1.499}
  - {origin: hand_base_link, task: ring_distal, origin_kp: 0, task_kp: 16, 
      task_offset: [-0.0135, 0.0, 0.0188], scale: 1.416}
    # pinky
  - {origin: hand_base_link, task: pinky_middle, origin_kp: 0, task_kp: 18, 
      scale: 1.665}
  - {origin: hand_base_link, task: pinky_distal, origin_kp: 0, task_kp: 19, 
      scale: 1.693}
  - {origin: hand_base_link, task: pinky_distal, origin_kp: 0, task_kp: 20, 
      task_offset: [-0.0135, 0.0, 0.0188], scale: 1.655}

  mediapipe_rotation:
    x: -7.0
    y: 0.0
    z: -100.0

render:
  camera:
    azimuth: 90
    elevation: 0.0
    distance: 0.7
