# Ability Hand - KeyVectorOptimizer (MediaPipe video/camera input)
# norm_delta=0.06: higher than AVP because monocular depth is noisier

optimizer:
  type: "KeyVectorOptimizer"

robot:
  type: "ability_hand"
  urdf_path: "assets/ability_hand/ability_hand_right.urdf"

retarget:
  huber_delta: 2.0
  norm_delta: 0.06
  lp_alpha: 0.4

  key_vectors:
    # thumb
  - {origin: base, task: thumb_L1, origin_kp: 0, task_kp: 2, scale: 0.453}
  - {origin: base, task: thumb_L2, origin_kp: 0, task_kp: 3, scale: 0.57}
  - {origin: base, task: thumb_tip, origin_kp: 0, task_kp: 4, scale: 0.858}
    # index
  - {origin: base, task: index_L1, origin_kp: 0, task_kp: 6, scale: 0.78}
  - {origin: base, task: index_L2, origin_kp: 0, task_kp: 7, scale: 0.885}
  - {origin: base, task: index_tip, origin_kp: 0, task_kp: 8, scale: 0.96}
    # middle
  - {origin: base, task: middle_L1, origin_kp: 0, task_kp: 10, scale: 0.774}
  - {origin: base, task: middle_L2, origin_kp: 0, task_kp: 11, scale: 0.878}
  - {origin: base, task: middle_tip, origin_kp: 0, task_kp: 12, scale: 0.954}
    # ring
  - {origin: base, task: ring_L1, origin_kp: 0, task_kp: 14, scale: 0.785}
  - {origin: base, task: ring_L2, origin_kp: 0, task_kp: 15, scale: 0.91}
  - {origin: base, task: ring_tip, origin_kp: 0, task_kp: 16, scale: 0.997}
    # pinky
  - {origin: base, task: pinky_L1, origin_kp: 0, task_kp: 18, scale: 0.835}
  - {origin: base, task: pinky_L2, origin_kp: 0, task_kp: 19, scale: 1.015}
  - {origin: base, task: pinky_tip, origin_kp: 0, task_kp: 20, scale: 1.152}

  mediapipe_rotation:
    x: 0.0
    y: -5.0
    z: 0.0

render:
  camera:
    azimuth: 180
    elevation: -20
    distance: 0.5
