# Unitree Dex5 - KeyVectorOptimizer (MediaPipe video/camera input)
# norm_delta=0.06: higher than AVP because monocular depth is noisier

optimizer:
  type: "KeyVectorOptimizer"

robot:
  type: "unitree_dex5_hand"

retarget:
  huber_delta: 2.0
  norm_delta: 0.06
  lp_alpha: 0.4

  key_vectors:
    # thumb
  - {origin: base_link00, task: Link_12R, origin_kp: 0, task_kp: 2, scale: 0.161}
  - {origin: base_link00, task: Link_13R, origin_kp: 0, task_kp: 3, scale: 0.299}
  - {origin: base_link00, task: Link_14R, origin_kp: 0, task_kp: 4, scale: 0.46}
    # index
  - {origin: base_link00, task: Link_22R, origin_kp: 0, task_kp: 6, scale: 0.608}
  - {origin: base_link00, task: Link_23R, origin_kp: 0, task_kp: 7, scale: 0.755}
  - {origin: base_link00, task: Link_24R, origin_kp: 0, task_kp: 8, scale: 0.769}
    # middle
  - {origin: base_link00, task: Link_32R, origin_kp: 0, task_kp: 10, scale: 
      0.637}
  - {origin: base_link00, task: Link_33R, origin_kp: 0, task_kp: 11, scale: 
      0.773}
  - {origin: base_link00, task: Link_34R, origin_kp: 0, task_kp: 12, scale: 
      0.783}
    # ring
  - {origin: base_link00, task: Link_42R, origin_kp: 0, task_kp: 14, scale: 
      0.678}
  - {origin: base_link00, task: Link_43R, origin_kp: 0, task_kp: 15, scale: 
      0.815}
  - {origin: base_link00, task: Link_44R, origin_kp: 0, task_kp: 16, scale: 
      0.826}
    # pinky
  - {origin: base_link00, task: Link_52R, origin_kp: 0, task_kp: 18, scale: 
      0.802}
  - {origin: base_link00, task: Link_53R, origin_kp: 0, task_kp: 19, scale: 
      0.961}
  - {origin: base_link00, task: Link_54R, origin_kp: 0, task_kp: 20, scale: 
      0.996}

  mediapipe_rotation:
    x: -90.0
    y: -90.0
    z: 0.0

render:
  camera:
    azimuth: 90
    elevation: -20
    distance: 0.5
    lookat: [0, 0, 0.05]
