# Linker L20 Configuration for Retargeting

optimizer:
  type: "AdaptiveOptimizerAnalytical"

robot:
  type: "linker_l20"

retarget:
  huber_delta: 2.0
  huber_delta_dir: 0.5
  norm_delta: 0.04
  w_pos: 5.0
  w_dir: 1.0
  project_tip_dir: false
  w_full_hand: 1.0
  pinch_scaling: 1.0
  alpha: 1.0
  segment_scaling:
    thumb: [0.946, 2.106, 1.011, 0.914]
    index: [1.682, 1.136, 1.063, 0.911]
    middle: [1.701, 1.124, 1.06, 0.923]
    ring: [1.689, 1.22, 1.243, 1.034]
    pinky: [1.706, 1.584, 1.922, 1.53]

  pinch_thresholds:
    index: {d1: 2.0, d2: 4.0}
    middle: {d1: 2.0, d2: 4.0}
    ring: {d1: 2.0, d2: 4.0}
    pinky: {d1: 2.0, d2: 4.0}

  mediapipe_rotation:
    x: -7.0
    y: 0.0
    z: -100.0

  lp_alpha: 0.4

render:
  camera:
    azimuth: 90
    elevation: 0.0
    distance: 0.7
