# Sharpa Hand Configuration for Retargeting
# 5 fingers, 22 DOF

optimizer:
  type: "AdaptiveOptimizerAnalytical"

robot:
  type: "sharpa_hand"

retarget:
  huber_delta: 2.0
  huber_delta_dir: 0.5
  norm_delta: 0.04
  w_pos: 5.0
  w_dir: 1.0
  project_tip_dir: false
  w_full_hand: 1.0

  pinch_scaling: 1.0
  alpha: 1.0
  segment_scaling:
    thumb: [0.662, 1.712, 1.14, 0.847]
    index: [1.111, 1.18, 1.052, 1.024]
    middle: [1.104, 1.167, 1.049, 1.037]
    ring: [1.062, 1.267, 1.231, 1.162]
    pinky: [1.065, 1.645, 1.903, 1.72]

  pinch_thresholds:
    index: {d1: 2.0, d2: 4.0}
    middle: {d1: 2.0, d2: 4.0}
    ring: {d1: 2.0, d2: 4.0}
    pinky: {d1: 2.0, d2: 4.0}

  mediapipe_rotation:
    x: -7.0
    y: 0.0
    z: -20.0

  lp_alpha: 0.4

render:
  camera:
    azimuth: 180
    elevation: -20
    distance: 0.5
