# LinkerHand L21 Configuration for Retargeting

optimizer:
  type: "AdaptiveOptimizerAnalytical"

robot:
  type: "linkerhand_l21"

retarget:
  huber_delta: 2.0
  huber_delta_dir: 0.5
  norm_delta: 0.04
  w_pos: 5.0
  w_dir: 1.0
  project_tip_dir: false
  w_full_hand: 1.0

  pinch_scaling: 1.0
  alpha: 1.0
  segment_scaling:
    thumb: [1.674, 0.466, 2.518, 0.521]
    index: [1.522, 1.012, 1.47, 0.866]
    middle: [1.574, 1.001, 1.465, 0.877]
    ring: [1.524, 1.086, 1.719, 0.983]
    pinky: [1.419, 1.41, 2.658, 1.455]

  pinch_thresholds:
    index: {d1: 2.0, d2: 4.0}
    middle: {d1: 2.0, d2: 4.0}
    ring: {d1: 2.0, d2: 4.0}
    pinky: {d1: 2.0, d2: 4.0}

  mediapipe_rotation:
    x: 0.0
    y: 0.0
    z: -20.0

  lp_alpha: 0.4

render:
  camera:
    azimuth: 180
    elevation: -20
    distance: 0.5
