# Linker L20 Configuration for Retargeting

optimizer:
  type: "AdaptiveOptimizerAnalytical"

robot:
  type: "linker_l20"

retarget:
  huber_delta: 2.0
  huber_delta_dir: 0.5
  norm_delta: 0.04
  w_pos: 5.0
  w_dir: 1.0
  project_tip_dir: false
  w_full_hand: 1.0
  pinch_scaling: 1.5101
  alpha: 1.0
  mcp_lateral_scale: 0.60
  thumb_scale: 1.0
  thumb_inward_offset: -0.02

  segment_scaling:
    thumb: [1.95, 1.727, 1.53, 1.417]
    index: [1.9, 1.617, 1.624, 1.579]
    middle: [1.88, 1.58, 1.548, 1.47]
    ring: [1.9, 1.613, 1.613, 1.55]
    pinky: [1.95, 1.806, 1.821, 1.74]

  pinch_thresholds:
    index: {d1: 2.0, d2: 4.0}
    middle: {d1: 2.0, d2: 4.0}
    ring: {d1: 2.0, d2: 4.0}
    pinky: {d1: 2.0, d2: 4.0}

  mediapipe_rotation:
    x: -10.0
    y: 0.0
    z: 100.0

  lp_alpha: 0.4

render:
  camera:
    azimuth: 90
    elevation: 0.0
    distance: 0.7
