# Ability Hand - KeyVectorOptimizer (Pico 4 input)

optimizer:
  type: "KeyVectorOptimizer"

robot:
  type: "ability_hand"
  urdf_path: "assets/ability_hand/ability_hand_right.urdf"

retarget:
  huber_delta: 2.0
  norm_delta: 0.04
  lp_alpha: 0.4

  key_vectors:
    # thumb
  - {origin: base, task: thumb_L1, origin_kp: 0, task_kp: 2, scale: 0.614}
  - {origin: base, task: thumb_L2, origin_kp: 0, task_kp: 3, scale: 0.75}
  - {origin: base, task: thumb_tip, origin_kp: 0, task_kp: 4, scale: 1.099}
    # index
  - {origin: base, task: index_L1, origin_kp: 0, task_kp: 6, scale: 0.813}
  - {origin: base, task: index_L2, origin_kp: 0, task_kp: 7, scale: 0.962}
  - {origin: base, task: index_tip, origin_kp: 0, task_kp: 8, scale: 1.056}
    # middle
  - {origin: base, task: middle_L1, origin_kp: 0, task_kp: 10, scale: 0.789}
  - {origin: base, task: middle_L2, origin_kp: 0, task_kp: 11, scale: 0.921}
  - {origin: base, task: middle_tip, origin_kp: 0, task_kp: 12, scale: 0.996}
    # ring
  - {origin: base, task: ring_L1, origin_kp: 0, task_kp: 14, scale: 0.805}
  - {origin: base, task: ring_L2, origin_kp: 0, task_kp: 15, scale: 0.96}
  - {origin: base, task: ring_tip, origin_kp: 0, task_kp: 16, scale: 1.052}
    # pinky
  - {origin: base, task: pinky_L1, origin_kp: 0, task_kp: 18, scale: 0.89}
  - {origin: base, task: pinky_L2, origin_kp: 0, task_kp: 19, scale: 1.072}
  - {origin: base, task: pinky_tip, origin_kp: 0, task_kp: 20, scale: 1.17}

  mediapipe_rotation:
    x: 0.0
    y: -5.0
    z: 0.0

render:
  camera:
    azimuth: 180
    elevation: -20
    distance: 0.5
